import type { NextPage } from "next";
import { ReactElement } from "react";
import Head from "next/head";
import Image from "next/image";
//import styles from "../styles/Home.module.css";
import {
  Box,
  Flex,
  VStack,
  Stack,
  Button,
  Text,
  useBreakpointValue,
  Container,
  Link,
  useColorModeValue,
  SimpleGrid,
  Center,
  Heading,
  Icon,
  HStack,
} from "@chakra-ui/react";
import { CheckIcon } from "@chakra-ui/icons";
//import { FcAssistant, FcDonate, FcInTransit } from "react-icons/fc";

interface FeatureProps {
  title: string;
  text: string;
  background: string;
}

const features = Array.apply(null, Array(8)).map(function (x, i) {
  return {
    id: i,
    title: "Lorem ipsum dolor sit amet",
    text: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam.",
  };
});

const Feature = ({ title, text }: FeatureProps) => {
  return (
    <Stack>
      {/* <Flex
        w={16}
        h={16}
        align={"center"}
        justify={"center"}
        color={"white"}
        rounded={"full"}
        bg={"gray.100"}
        mb={1}
      ></Flex> */}
      <Text fontWeight={1000}>{title}</Text>
      <Text color={"gray.600"}>{text}</Text>
    </Stack>
  );
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Unipp:Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex
          w={"full"}
          h={"100vh"}
          backgroundImage={
            "url(https://images.unsplash.com/photo-1600267175161-cfaa711b4a81?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80)"
          }
          backgroundSize={"cover"}
          backgroundPosition={"center center"}
        >
          <VStack
            w={"full"}
            justify={"center"}
            px={useBreakpointValue({ base: 4, md: 8 })}
            bgGradient={"linear(to-r, blackAlpha.600, transparent)"}
          >
            <Stack maxW={"2xl"} align={"flex-start"} spacing={6}>
              <Text
                color={"white"}
                fontWeight={700}
                lineHeight={1.2}
                fontSize={useBreakpointValue({ base: "3xl", md: "4xl" })}
              >
                大学生のためのアプリUnipp
              </Text>
              <Stack direction={"row"}>
                <Button
                  bg={"whiteAlpha.300"}
                  rounded={"full"}
                  color={"white"}
                  _hover={{ bg: "whiteAlpha.500" }}
                  as="a"
                  href="https://google.com"
                >
                  今すぐ使ってみる
                </Button>
              </Stack>
            </Stack>
          </VStack>
        </Flex>
        <Box py={32}>
          <Center
            color={"black"}
            fontWeight={700}
            lineHeight={1.2}
            fontSize={useBreakpointValue({ base: "3xl", md: "4xl" })}
            p={6}
          >
            Unippとは
          </Center>
          <SimpleGrid columns={{ base: 1, md: 3 }} spacing={10}>
            <Feature
              title={"近くの大学生と情報共有できる"}
              text={"学外の大学生と幅広いコミュニケーションを提供"}
              background={"white"}
            />
            <Feature
              title={"地域ごとに情報が分かれている"}
              text={
                "いいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいいい"
              }
              background={"white"}
            />
            <Feature
              title={"他大学にも情報発信できる"}
              text={
                "うううううううううううううううううううううううuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"
              }
              background={"black"}
            />
          </SimpleGrid>
        </Box>
        <Stack
          py={useBreakpointValue({ base: "32", md: "0" })}
          background={useBreakpointValue({ base: "red", md: "green" })}
        >
          <Box p={4} background={"gray.100"}>
            <Stack spacing={4} as={Container} maxW={"3xl"} textAlign={"center"}>
              <Heading fontSize={"3xl"}>対応大学</Heading>
              <Text color={"gray.600"} fontSize={"xl"}>
                1000校以上の大学(短期大学を含む)に対応！！
              </Text>
            </Stack>
            <Container maxW={"6xl"} mt={10}>
              <SimpleGrid columns={{ base: 1, md: 2, lg: 4 }} spacing={10}>
                <HStack align={"top"}>
                  <Box color={"green.400"} px={2}>
                    <Icon as={CheckIcon} />
                  </Box>
                  <VStack align={"start"}>
                    <Text fontWeight={600}>あいうえお</Text>
                    <Text color={"gray.600"}>かきくけこ</Text>
                  </VStack>
                </HStack>
              </SimpleGrid>
            </Container>
          </Box>
        </Stack>
        <Box
          bg={useColorModeValue("gray.200", "gray.900")}
          color={useColorModeValue("gray.700", "gray.200")}
        >
          <Container
            as={Stack}
            maxW={"6xl"}
            py={4}
            direction={{ base: "column", md: "row" }}
            spacing={4}
            justify={{ base: "center", md: "space-between" }}
            align={{ base: "center", md: "center" }}
          >
            <Stack direction={"row"} spacing={6}>
              <Link href={"#"}>Home</Link>
              <Link href={"#"}>About</Link>
              <Link href={"#"}>Blog</Link>
              <Link href={"#"}>Contact</Link>
            </Stack>
            <Text>© 2021 Chakra Templates. All rights reserved</Text>
          </Container>
        </Box>
      </main>
    </>
  );
};

export default Home;
