import type { NextPage } from "next";
import Head from "next/head";
// import { EventCard } from "../../components/Organisms/EventCard";
import { Box, Flex, Spacer, Text } from "@chakra-ui/layout";
// import dayjs from "dayjs";
// import { MyPage } from "../../components/Layouts/MyPage";
// import { ReactElement, ReactNode, useEffect, useState } from "react";
// import { Avatar } from "@chakra-ui/avatar";
// import { useBreakpointValue } from "@chakra-ui/media-query";
// import { TriangleDownIcon } from "@chakra-ui/icons";

// export const Job = () => {
//   return(
//     <h1>pp</h1>
//   )
// }

const JobPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Unipp:JobPage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>dummy code</h1>
      </main>
    </>
  )
}

export default JobPage